Rename genanki.py to create_anki_deck.py to fix circular import
Fixes "AttributeError: partially initialized module 'genanki' has no attribute 'Model' (most likely due to a circular import)"

See: https://stackoverflow.com/a/62145654/9907540